server:
  port: 8021
  shutdown: graceful
  name: htPlatform
  http2:
    enabled: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
springdoc:
  api-docs.enabled: true
  packages-to-scan: com.cknb.htPlatform
  swagger-ui.path: /api/app/swagger-ui
  api-docs.path: /api/app/api-docs
  api-docs.groups.enabled: true
  cache.disabled: true
  default-consumes-media-type: application/json;charset=UTF-8

spring:
  http:
    multipart:
      enabled: false
  datasource:
    url: jdbc:log4jdbc:mysql://hiddentag.cz5fx5xtsihl.ap-southeast-1.rds.amazonaws.com:9306/hiddentag?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: cknb_data_report
    password: cknb_data_report
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
  # thymeleaf
    thymeleaf:
      cache: false
  application:
    name: htTotalApp
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: info
      org.hibernate.type: trace
#  # 스케줄러
#  task:
#    scheduling:
#      pool:
#        size: 5
#      thread-name-prefix: "scheduler-"
#    execution:
#      shutdown:
#        await-termination: true
#        await-termination-period: 60s
  ## thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #Redis
  data:
    redis:
#      host: 52.77.138.41  # test server
      host: ${REDIS_HOST:192.168.0.14}  # local
      port: ${REDIS_PORT:6379}
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    # 전체 애플리케이션 로그 레벨
    com.cknb.htPlatform: INFO
    # 스케줄러만 따로 설정
    com.cknb.htPlatform.scheduler: INFO
    # SQL 로그 줄이기 (log4jdbc)
    log4jdbc.log4j2: WARN
    # HikariCP 경고 로그 줄이기
    com.zaxxer.hikari: WARN
    # 스프링 스케줄링 로그 줄이기
    org.springframework.scheduling: WARN

    com.example.log: debug
    org:
      springframework:
        scheduling: debug
  logback:
    rollingpolicy:
      max-history: 7
  file:
    name: /var/log/server.log

  # AES Key
aes:
  key: 2021.06.03.cknb.hiddentagiqr.com

application:
  urls:
    # CKNB Admin 사이트 입니다.
    admin: http://hiddentagiqr.com
    wAdmin: http://www.hiddentagiqr.com
    data_report: http://hiddentagiqr.com:8020/
  security:
    # 데이터 보고서 URL 체크 여부(true : urls-admin 통해서만 접근 가능 / false : 체크 안함)
    referer-check-enabled: false
